//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsXuezi.UserControls.MultiPics {
    
    
    public partial class Multi {
        
        /// <summary>
        /// Pics1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl Pics1;
        
        /// <summary>
        /// MultiPic1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic1;
        
        /// <summary>
        /// MultiPic2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic2;
        
        /// <summary>
        /// MultiPic3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic3;
        
        /// <summary>
        /// MultiPic4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic4;
        
        /// <summary>
        /// MultiPic5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic5;
        
        /// <summary>
        /// MultiPic6 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic6;
        
        /// <summary>
        /// MultiPic7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic7;
        
        /// <summary>
        /// MultiPic8 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic8;
        
        /// <summary>
        /// MultiPic9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic9;
        
        /// <summary>
        /// MultiPic10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::UsXuezi.UserControls.CKPic MultiPic10;
    }
}
